# ---------------------------*-python-*----------------------------------------#
# file   __init__.py
# author mathew cleveland
# date   February 2019
# note   Copyright (C) 2019, Los Alamos National Security, LLC.
#        All rights reserved.
# -----------------------------------------------------------------------------#
'''
The Output Parse-Pickle-Plot Python (OPPPY) library is a python based data
analysis library designed to extract, store, and plot information from output
and dump files generated by scientific software packages.

'''

from opppy import dump_utils
from opppy import interactive_utils
from opppy import output
from opppy import plot_dictionary
from opppy import plot_dump_dictionary
from opppy import plotting_help
from opppy import progress
from opppy import version


__all__ = ['dump_utils', 'interactive_utils', 'output', 
            'plot_dictionary', 'plot_dump_dictionary', 'plotting_help',
            'progress', 'version', 'tally']
